### ISSUE TITLE
关于算法矩阵的大小问题

### ISSUE THREAD

**Issue by Just4Uzi** [rainarch/SentiBridge#2]
您好，在复现这个代码的过程中发现，如果语料很大，提取出的pair和patt很多，那么构建的pair-patt映射关系矩阵会很大。比如我现在10W语料的patt有120W+，pair有45W+，这个时候应该怎么处理呢。你们使用的语料规模是多少呢

**Comment by luckymail** [comment]
@SlashChven 你好，
我是该项目的开发人员，矩阵过大无法计算可以通过以下方法解决：
1. 稀疏矩阵过大可以通过压缩存储解决
2. 运算时，可以单独抽取出一列和一行进行计算
我们的语料规模以最大的新闻领域来看，pair约120w（你是45w）所以按照上面的方法可以解决问题。

**Comment by Just4Uzi** [comment]
@luckymail 今天天气真好哈，感谢您的指点~祝您每天都有好心情！

**Comment by Just4Uzi** [comment]
@luckymail 还要麻烦问下您，我用稀疏矩阵的方式存储，每次抽一行一列进行计算，内存的问题解决了，但是效率有点慢，不知道你们大约运行了多场时间，迭代了多少次呢？

**Comment by luckymail** [comment]
@SlashChven 你好，可以尝试用四个哈希表来分别存储：pattern分数向量、pair分数向量、关系矩阵B、关系矩阵B的转置，其中key是相应的pair或者pattern，value是其分数。关系矩阵B和关系矩阵B的转置是二级哈希表，结构上pair和pattern顺序相反即可实现转置。
效率没有精确统计过，默认迭代100次（已经收敛），时间按照新闻pair（120w数据量）预计10个小时以内。

**Comment by Just4Uzi** [comment]
@luckymail 多谢！按照您说的现在的效率已经有了很大的提升，不过好像还是没达到100迭代10个小时之内的效率，我打算先跑一下看看结果，再看看哪里可以继续优化~
