### ISSUE TITLE
关于迭代终止条件

### ISSUE THREAD

**Issue by zhuyuuyuhz** [rainarch/SentiBridge#8]
你好，在您的论文中，排序部分的迭代终止条件是Ci和Ci+1之间的所有项的差值小于1E-7，但是在您的代码中，迭代终止的条件好像并不是这样的，默认是迭代次数100次结束，请问这个理解对吗？这样做的目的是什么？

**Comment by rainarch** [comment]
你可以尝试两种做法，会发现结果基本一致。
